FROM node:lts as builder

ARG WEB_OAUTH_CLIENT
ENV WEB_OAUTH_CLIENT=$WEB_OAUTH_CLIENT
ARG AM_URL
ENV AM_URL=$AM_URL
ARG APP_URL
ENV APP_URL=$APP_URL
ARG API_URL
ENV API_URL=$API_URL
ARG DEBUGGER_OFF
ENV DEBUGGER_OFF=$DEBUGGER_OFF
ARG REALM_PATH
ENV REALM_PATH=$REALM_PATH
ARG JOURNEY_LOGIN
ENV JOURNEY_LOGIN=$JOURNEY_LOGIN
ARG JOURNEY_REGISTER
ENV JOURNEY_REGISTER=$JOURNEY_REGISTER

WORKDIR /app/builder
RUN npm i -g nx

COPY . /app/builder 
RUN npm install

RUN nx run-many --target=build --projects=reactjs-todo,todo-api --skipNxCache
