FROM node:lts as builder

ARG WEB_OAUTH_CLIENT
ARG AM_URL
ARG APP_URL
ARG API_URL
ARG DEBUGGER_OFF
ARG REALM_PATH
ARG JOURNEY_LOGIN
ARG JOURNEY_REGISTER

WORKDIR /app/builder
RUN npm i -g nx

COPY . /app/builder 
RUN npm install

RUN WEB_OAUTH_CLIENT=$WEB_OAUTH_CLIENT AM_URL=$AM_URL APP_URL=$APP_URL API_URL=$API_URL DEBUGGER_OFF=$DEBUGGER_OFF REALM_PATH=$REALM_PATH JOURNEY_REGISTER=$JOURNEY_REGISTER JOURNEY_LOGIN=$JOURNEY_LOGIN nx run-many --target=build --projects=reactjs-todo,todo-api --skipNxCache
