version: '3.8'

networks:
  corp:
    driver: bridge

services:
  todo-api:
    container_name: todo-api
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        AM_URL: $AM_URL
        APP_URL: $APP_URL
        API_URL: 'https://todo-api-ryanbas21.cloud.okteto.net'
        DEBUGGER_OFF: $DEBUGGER_OFF
        REALM_PATH: $REALM_PATH
        JOURNEY_LOGIN: $JOURNEY_LOGIN
        JOURNEY_REGISTER: $JOURNEY_REGISTER
        WEB_OAUTH_CLIENT: $WEB_OAUTH_CLIENT
    command: node /app/builder/dist/samples/todo-api/main.js
    env_file:
      - ./samples/todo-api/.env
    ports:
      - 8081:8081
    environment:
      PORT: 8081
      AM_URL: $AM_URL
      APP_URL: $APP_URL
      API_URL: 'https://todo-api-ryanbas21.cloud.okteto.net'
      DEBUGGER_OFF: $DEBUGGER_OFF
      REALM_PATH: $REALM_PATH
      JOURNEY_LOGIN: $JOURNEY_LOGIN
      JOURNEY_REGISTER: $JOURNEY_REGISTER
      WEB_OAUTH_CLIENT: $WEB_OAUTH_CLIENT
      REST_OAUTH_CLIENT: $REST_OAUTH_CLIENT
      REST_OAUTH_SECRET: $REST_OAUTH_SECRET

    networks:
      - corp
    restart: on-failure

  reactjs-todo:
    container_name: reactjs-todo
    build:
      context: ./
      dockerfile: ./samples/reactjs-todo/Dockerfile
    ports:
      - 8443:8081
    restart: on-failure
