 [build.environment]
 [build]
  command = "npm install; npx nx run autoscript-apps:build"
  publish = "../../dist/e2e/autoscript-apps/"

[dev]
  command = "npx nx run autoscript-apps:serve"
  targetPort = 4200 