 [build.environment]
   NPM_FLAGS="--version"
   TERM = "xterm"
 [build]
  command = "npx nx run autoscript-apps:build"
  publish = "../../dist/e2e/autoscript-apps/"

[dev]
  command = "npx nx run autoscript-apps:serve"
  targetPort = 4200 