name: Playwright Tests
on:
  pull_request:
    branches:
      - develop
      - master
      - release-*
jobs:
  linux:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Generate certificates for next step
      uses: kofemann/action-create-certificate@v0.0.4
      with:
        hostcert: 'example.com+5.pem'
        hostkey:  'example.com+5-key.key'
        cachain:  'ca-chain.pem'
    - name: Use generated certificates
      run: | 
          openssl x509 -in example.com+5.pem -noout -text
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm i -g npm@7
    - run: npm ci
      env:
        DEBUG: pw:install
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    - run: npm run build
    - run: npx playwright install --with-deps ${{ matrix.browser }}
    - run: npm run test:e2e -- --project=${{ matrix.browser }}
  osx:
      name: ${{ matrix.os }} (${{ matrix.browser }})
      strategy:
        fail-fast: false
        matrix:
          browser: [chromium, firefox, webkit]
          os: [macos-10.15, macos-11.0]
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i -g npm@7
      - run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run build
      - run: npx playwright install --with-deps ${{ matrix.browser }} chromium 
      - run: npm run test:e2e -- --project=${{ matrix.browser }}







































































































































































































































































































































































































































































































































































































































































































































