name: ForgeRock Windows CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  pr:
    runs-on: windows-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup custom host for sdkapp.example.com
        run: echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" >> C:\Windows\System32\drivers\etc\hosts #add to new line

      - uses: actions/setup-node@v1
        with: 
          node-version: '14'

      - name: npm install
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_BROWSERS_PATH: 0
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=3 --base=remotes/origin/develop
      - run: npx nx affected --target=test --parallel --max-parallel=2 --base=remotes/origin/develop
      - run: npx nx affected --target=test --configuration=integration --parallel --max-parallel=2 --base=remotes/origin/develop
      - run: npx nx affected --target=e2e  --parallel --max-parallel=2 --base=remotes/origin/develop
      - run: npx nx-cloud stop-all-agents

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() || success() }}
        with:
          name: 'E2E Artifacts'
          path: test-results/
          retention-days: 5
  agents:
    runs-on: windows-latest
    name: Agent Windows 
    timeout-minutes: 10
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
